<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>贷前管理</title>
<?php new Ui_Common_Chedai_Meta(); ?>
</head>
<body class="salesmanbefore-page">
<script type="text/javascript" src="/js/rem.js"></script>
	<a class="btn btn-block btn-blue" href="/chedai/salesman_customerlist">客户信息管理<i class="client"></i></a>
	<a class="btn btn-block btn-blue" href="/chedai/salesman_carlist">车辆信息管理<i class="car"></i></a>
	<a class="btn btn-block btn-blue" href="/chedai/salesman_loanlist">贷款额度确认<i class="money"></i></a>
</body>
</html>
