<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>车辆照片</title>
<?php new Ui_Common_Chedai_Meta(); ?>
<link rel="stylesheet" type="text/css" href="/css/photoswipe.css">
<link rel="stylesheet" type="text/css" href="/css/default-skin/default-skin.css">
</head>
<body data-id="<?php echo $id;?>">
<script type="text/javascript" src="/js/rem.js"></script>
<form>
    <ul class="form clearfix list-img">
    <?php foreach($data as $v):?>
    	<li class="img-uploader">
	            <div class="img-uploader-box">
            		<a href="<?php echo $v['src'];?>" data-size="<?php echo $v['size'];?>" data-author="<?php echo $v['name'];?>">
	                <img src="<?php echo $v['src'];?>">
	            	</a>
	            </div>
	            <p class="tac"><?php echo $v['name'];?></p>
	    </li>
	<?php endforeach;?>
    </ul>
</form>
<div class="wrapper">
    <a class="btn btn-block btn-default" href="javascript:;" id="next-step2" onclick="javascript:history.go(-1);">上一步</a>
</div>
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
    <!-- Background of PhotoSwipe. 
         It's a separate element as animating opacity is faster than rgba(). -->
    <div class="pswp__bg"></div>
    <!-- Slides wrapper with overflow:hidden. -->
    <div class="pswp__scroll-wrap">
        <!-- Container that holds slides. 
            PhotoSwipe keeps only 3 of them in the DOM to save memory.
            Don't modify these 3 pswp__item elements, data is added later on. -->
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>
        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
        <div class="pswp__ui pswp__ui--hidden">
            <div class="pswp__top-bar">
                <!--  Controls are self-explanatory. Order can be changed. -->
                <div class="pswp__counter"></div>
                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                <!-- <button class="pswp__button pswp__button--share" title="Share"></button> -->
                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                <!-- element will get class pswp__preloader--active when preloader is running -->
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                        <div class="pswp__preloader__donut"></div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div> 
            </div>
            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
            </button>
            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
            </button>
            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>
        </div>
    </div>
</div>
<!-- <script type="text/javascript" src="/js/chedai/carinfophoto.js"></script> -->
<script src="/js/photoswipe.min.js"></script>
<script src="/js/photoswipe-ui-default.min.js"></script>
<script src="/js/photoscale.js"></script>
</body>
</html>
