<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>车辆业务</title>
<?php new Ui_Common_Chedai_Meta(); ?>
</head>
<body class="salesmancar-page">
<script type="text/javascript" src="/js/rem.js"></script>
	<a class="btn btn-block btn-blue" href="/chedai/salesman_before">贷前管理</a>
	<a class="btn btn-block btn-disabled" href="javascript:;">贷中管理<i></i></a>
	<a class="btn btn-block btn-disabled" href="javascript:;">贷后管理<i></i></a>
</body>
</html>
