<!-- BEGIN FOOTER -->
<!--	<div class="footer">-->
<!--		<div class="footer-inner">-->
<!--			2015-2016 &copy; 银巴克风控后台-->
<!--		</div>-->
<!--		<div class="footer-tools">-->
<!--			<span class="go-top">-->
<!--			<i class="icon-angle-up"></i>-->
<!--			</span>-->
<!--		</div>-->
<!--	</div>-->
	<!-- END FOOTER -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<script src="/js/jquery-1.10.1.min.js" type="text/javascript"></script>
	<script src="/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
	<script src="/js/bootstrap.min.js" type="text/javascript"></script>
	<!--[if lt IE 9]>
	<script src="/js/excanvas.min.js"></script>
	<script src="/js/respond.min.js"></script>  
	<![endif]-->   
	<script src="/js/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="/js/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="/js/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="/js/jquery.uniform.min.js" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<script src="/js/bootstrap-modal.js" type="text/javascript" ></script>
	<script src="/js/bootstrap-modalmanager.js" type="text/javascript" ></script>
	<script src="/js/app.js"></script>
    <script src="/script/jquery-messager.js"></script>
    <script src="/script/jquery-dialog.js"></script>
	<script>
		jQuery(document).ready(function() {       
		   // initiate layout and plugins
		   App.init();
		   //UIModals.init();
		});

        $('.modifypwd').on('click',function(){
            $.fn.dialog({href:'/index/modifypasswd/', title: '修改密码', height:260, width:550});
        });

	</script>
<!-- END BODY -->
</html>