<!-- BEGIN SIDEBAR -->
		<div class="page-sidebar nav-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->        
			<ul class="page-sidebar-menu">
				<li>
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler hidden-phone"></div>
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
				</li>
				<li>
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                    <!--
                    <?php foreach ($menus as $menu):?>
                        <div title="<?php echo $menu['name'];?>" style="overflow:auto;">
                            <ul class="easyui-tree">
                                <?php foreach ($menu['children'] as $child):?>
                                    <li><span><a href="<?php echo $child['murl'];?>" target='content'><?php echo $child['mname'];?></a></span></li>
                                <?php endforeach;?>
                            </ul>
                        </div>
                    <?php endforeach;?>
                    -->
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				</li>
				<!--<li class="start ">
					<a href="index.html">
					<i class="icon-home"></i> 
					<span class="title">首页</span>
					</a>
				</li>-->
                <?php foreach ($menus as $menu):?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-user"></i>
                        <span class="title"><?php echo $menu['name'];?></span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <?php foreach ($menu['children'] as $child):?>
                            <?php if($child['murl'] == $_SERVER['REQUEST_URI']) {?>
                            <li class="active">
                            <?php }else{ ?>
                            <li class="">
                            <?php } ?>
                                <a href="<?php echo $child['murl'];?>" ><?php echo $child['mname'];?></a>
                            </li>
                        <?php endforeach;?>
                    </ul>
                </li>
                <?php endforeach;?>

				<!--<li class="active ">
					<a href="javascript:;">
					<i class="icon-th"></i> 
					<span class="title">Data Tables</span>
					<span class="selected"></span>
					<span class="arrow open"></span>
					</a>
					<ul class="sub-menu">
						<li class="active">
							<a href="table_basic.html">
							Basic Tables</a>
						</li>
					</ul>
				</li>-->

                <!--<li class="last ">
					<a href="charts.html">
					<i class="icon-bar-chart"></i>
					<span class="title">Visual Charts</span>
					</a>
				</li>-->
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
		<!-- END SIDEBAR -->
		
		