<?php new Ui_Common_Header();?>
<style>
@media screen and (min-width: 768px) { 
  .modal:before {
    display: inline-block;
    vertical-align: middle;
    content: " ";
    height: 100%;
  }
}

.modal-dialog {
  display: inline-block;
  text-align: left;
  vertical-align: middle;
}
</style>
<!-- BEGIN BODY -->
<body class="page-header-fixed">
<?php new Ui_Common_Navi();?>
<!-- BEGIN CONTAINER -->
<div class="page-container row-fluid">
<?php new Ui_Common_Sidebar();?>
<!-- BEGIN PAGE -->
<div class="page-content">
<!-- BEGIN PAGE CONTAINER-->        
	<div class="container-fluid">
		<!-- BEGIN PAGE HEADER-->
		<div class="row-fluid">
			<!-- END BEGIN STYLE CUSTOMIZER -->  
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">
				待制作合同</small>
			</h3>
			<ul class="breadcrumb">
				<?php echo Utils_View::breadcrumb([]);?>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
		<!-- BEGIN PAGE CONTENT-->          
		<div class="row-fluid">
			<div class="span12">
			<div class="portlet box light-grey">
				<div class="portlet-title">
					<div class="caption"><i class="icon-globe"></i>待制作合同</div>
				</div>

				<div class="portlet-body">
				
						
                        
					<div class="clearfix" style="display:none">


						<div class="btn-group">
							<select name="filterAssigner" class=""> 
								<option value="-1">全部</option>
								<option value="0">未分配</option>
								<?php //foreach ($users as $user):?>
								<option value="<?php //echo $user['id'];?>"><?php //echo $user['realname'];?></option>
								<?php// endforeach;?>
							</select>
						</div>

						<div class="clearfix">

								借款人姓名：<input id="borrower_name" name="borrower_name"  type="search" placeholder="" style="width:100px;height=15px;">
								报单人姓名：<input id="report_user_name" name="report_user_name" type="search" placeholder="" style="width:100px;height=15px;">

								创建时间:<div class="input-append date form_datetime">
									<input id="start_time" class="m-wrap date-picker app_form_field" style="width:100px;" type="text" name="start_time"  app_form_type="date" value="">
									<span class="add-on"><i class="icon-calendar"></i></span>
								</div>-
								<div class="input-append date form_datetime">
									<input id="end_time" class="m-wrap date-picker app_form_field" style="width:100px;"  type="text" name="end_time"  app_form_type="date" value="">
									<span class="add-on"><i class="icon-calendar"></i></span>
								</div>

								<div class="btn-group">

									<button id="risk_search" class="btn green">

									搜索 <i class="icon-search"></i>

									</button>
								</div>
								<div class="btn-group">

									<button id="export" class="btn green">

									导出 <i class="icon-share"></i>

									</button>
								</div>

							</div>

					</div>
					<table class="table table-striped table-bordered table-hover" id="assignList">
						<thead>
							<tr>
								<th>业务编号</th>
								<!-- <th>订单号</th> -->
								<th>客户姓名</th>
                                                                
								<th >客户手机号</th>
								<th>贷款金额（万）</th>
                                                                <th>贷款利率（%）</th>
								<th>贷款期限（月）</th>
								<th>创建时间</th>
								<th>操作</th>
								<!-- <th>约谈利息</th>
								<th>报单人姓名</th>
								<th>报单人电话</th>
								<th class="hidden-480">抵押物评估值</th>
								<th class="hidden-480">批贷金额</th>
								<th class="hidden-480">批贷期限</th>
								<th class="hidden-480">放款日期</th>
								<th class="hidden-480">业务区域</th>  -->
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>

		</div>
		</div>
	</div>
</div>
</div>
</body>
<?php new Ui_Common_Footer();?>
<script src="/script/jquery-messager.js"></script>
<script src="/script/jquery-dialog.js"></script>
<script type="text/javascript" src="/js/select2.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="/js/DT_bootstrap.js"></script>

<!-- 选择时间的JS -->
<script src="/script/IDValidator.js"></script> 
<script type="text/javascript" src="/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/js/bootstrap-datepicker.zh-CN.js"></script>
<script type="text/javascript" src="/script/form.js"></script>
<script>
var pglobal = {
	dt: null
}
								
$(document).ready(function(){
	pglobal.dt = $('#assignList').on('preXhr.dt', function ( e, settings, data ) {
			data.risker = $('select[name=filterAssigner]').val(),
			data.borrower_name = $('input[name=borrower_name]').val(),
			data.report_user_name = $('input[name=report_user_name]').val(),
			data.start_time = $('input[name=start_time]').val(),
			data.end_time = $('input[name=end_time]').val()
			
	    }).DataTable({
		lengthChange: false,
		processing: true,
		serverMethod: 'POST',
		serverSide: true,
		sort: false,
		searching: false,
		language: {
		  info: '显示 _START_ 到 _END_ ，一共  _TOTAL_ 条记录',
		  emptyTable: '没有记录',
	      paginate: {
	        previous: "上一页",
	        next: "下一页"
	      }
	    },
	    columnDefs:[
    		{targets:0, data:'id'},
    		// {targets:1, data:'no'},
    		{targets:1, data:'name'},
            {targets:2, data:'phone'},
    		{targets:3, data:'amount'},
            {targets:4, data:'rate'},
    		{targets:5, data:'deadline'},
    		{targets:6, data:'created_date'},
    		{targets:7, data:'id', render:function(data, type, full, meta) {
    			var html = '<a href="/contract/view/aid/'+data+'">查看</a> ';
    			return html;
    		}},
    		/*{targets:11, data:'seller_rate'},
                {targets:12, data:'creator_name'},
    		{targets:13, data:'creator_phone'}
    		{targets:9, data:'name', render:function(data, type, full, meta) {
    			return '';
    		}},
    		{targets:10, data:'name', render:function(data, type, full, meta) {
    			return '';
    		}},
    		{targets:11, data:'name', render:function(data, type, full, meta) {
    			return '';
    		}},
    		{targets:12, data:'name', render:function(data, type, full, meta) {
    			return '';
    		}},
    		{targets:13, data:'name', render:function(data, type, full, meta) {
    			return '';
    		}}*/
    	],
		"ajax": {
			url:'/contract/contranctMakeAjax/',
		}
	})

	$(document).on('click', '.jDialog-cancel-btn', function(){
		$.fn.dialog('close')
	});

	

	//导出下户专员列表excel
	$(document).on('click', '#export', function(){
		var borrower_name = $('#borrower_name').val();
		var report_user_name = $('#report_user_name').val();
		var risker_name = $('#risker_name').val();
		var start_time = $('#start_time').val();
		var end_time = $('#end_time').val();
		var risker = $('select[name=filterAssigner]').val();
		window.location.href='/app/exportRiskList?borrower_name='+borrower_name+'&report_user_name='+report_user_name+'&risker_name='+risker_name+'&start_time='+start_time+'&end_time='+end_time+'&risker='+risker
	});
	
	//点击搜索重新查询
	$(document).on('click', '#risk_search', function(){
		pglobal.dt.ajax.reload()
	});
	
	$(document).on('click', '.riskUserLnk', function () {
		var id = $(this).attr('for');
		$.fn.dialog({href:'/app/riskAuditForm/id/'+id, title: '分配下户人员'});
	})

	$(document).on('click', '#riskAuditSubBtn', function() {
		var aid = parseInt($('input[name=assign_aid]').val())
		var user = parseInt($('select[name=assign_user]').val())

		if (aid <= 0) return
		if (user <= 0) {
			$.messager.alert('提示', '请选择下户人员');
			return
		}

		$.post('/app/riskAudit/', {
			aid: aid,
			uid: user
		}, function(data) {
			if (data.error == '0') {
				$.messager.alert('提示', '操作成功', function(){
					$.fn.dialog('close');
					pglobal.dt.ajax.reload()
				});
			} else {
				$.messager.alert('提示', data.errmsg);
			}
		}, 'json')
	})

	$('select[name=filterAssigner]').change(function(){
		pglobal.dt.ajax.reload()
	})

})
</script>