<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>银代代风控系统</title>
<?php new Ui_Common_Chedai_Meta(); ?>
</head>
<body>
<script type="text/javascript" src="/js/rem.js"></script>
<ul class="logo">
    <li><i></i></li>
    <li><i></i></li>
</ul>
<ul class="wrapper login">
    <li>
        <input type="tel" maxlength="11" placeholder="请输入帐号" name="loginname">
    </li>
    <li>
        <input type="password" maxlength="20" placeholder="请输入密码" name="password">
    </li>
</ul>
<div class="wrapper">
    <a class="btn btn-block btn-blue" href="javascript:;" id="btn-submit">登录</a>
</div>
<script type="text/javascript" src="/js/chedai/login.js"></script>
</body>
</html>
